### PR TITLE
Basic support for nimble

### PR DESCRIPTION
**Pull request by mantielero**
Disclaimer: I am not a pro-dev, and this among my first PR's ever.
Main changes:
1. added a basic nimble file.
2. new folder structure (consistent with nimble)
3. created a `cinterop.nim` which imports and exports the whole library.
4. Added some `nim.cfg` files for the `tests` directory, so that the library looks local.

So now:
a. You can install it like:
```
nimble install
```
or 
```
nimble install <github address>
```
b. In order to use the library you just need:
```
import cinterop
```
c. For the `tests` folder, you don't need to use a relative path to reach the library.

I hope I saved you some effort. Feel free to modify as you wish.

### CODE REVIEW

**Comment by n0bra1n3r** [comment]
Incredible! I've never used nimble before, so was wondering how I would support it - you definitely saved me some time. Will take a look after work. Thank you for the PR!

**Comment by napalu** [comment]
@mantielero in your pull request, you define the license in the nimble file as BSD (I suppose you mean zero-clause BSD?) - why not just use the MIT license under which nim itself is licensed?

**Comment by mantielero** [comment]
No reason. I just created the structure basis. I let the license decision to @n0bra1n3r. MIT sounds good to me too.

**Comment by n0bra1n3r** [comment]
Merging, thank you! Will push a commit to change the license to MIT in staging.

**Pull request merged**
